name 'mbp_workstation_cookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mbp_workstation_cookbook'
long_description 'Installs/Configures mbp_workstation_cookbook'
version '0.1.0'
